### ISSUE TITLE
"Output directory not exists" during compile

### ISSUE THREAD

**Issue by glory-man** [lvgl/lv_i18n#35]
I used 
    npx lv_i18n compile -t "./src/translations/*.yml" -o "./src/lv_i18n/"

and received 

  npx: installed 28 in 4.243s
  Base locale 'en-GB' (autodetected)
  Output directory not exists (src/lv_i18n/)

Worked only if I manually create target directory (mkdir). Is it normally ?

**Comment by puzrin** [comment]
> Is it normally ?

Yes. Usually you only update data in existing directories (except first init). Auto-create can cause garbage on typos.
