### ISSUE TITLE
use lv_i18n_language_pack as default language pack during init

### ISSUE THREAD

**Issue by glory-man** [lvgl/lv_i18n#36]
so we can call
`lv_i18n_init(NULL);`
without using external constant lv_i18n_language_pack

If someone needs lv_i18n_language_pack data (such us "locale_name") yo can add some functions to generated c-api, such as
`int lv_i18n_get_locales_num(void) // gets total count of locales in activated current_lang_pack`
`const char * lv_i18n_get_locale_name(int locale_idx) // gets locale name from current_lang_pack by it id`

**Comment by glory-man** [comment]
If someone needs lv_i18n_language_pack data (such us "locale_name") yo can add some functions to  c-api, for example

int lv_i18n_get_locales_num(void)  // gets total count of locales in activated current_lang_pack
{
  if(current_lang_pack)
  {
    for(int i = 0; ; i++)
      if(current_lang_pack[i] == NULL)
        return i;
  }
  return 0;
}

const char * lv_i18n_get_locale_name(int locale_idx)  // gets locale name from current_lang_pack by it id 
{
  if((locale_idx < 0) || (locale_idx > lv_i18n_get_locales_num()))
    return NULL;
  
  return current_lang_pack[locale_idx]->locale_name;
}

**Comment by puzrin** [comment]
I don't understand added value of this request, please, clarify. Also, please, format you post with markdown, it's not readable now.

**Comment by glory-man** [comment]
Generated files lv_i18n.c/h implemented as an isolated module. To initilize module I need to call _lv_i18n_init()_ with an argument value equal to _lv_i18n_language_pack_ which is defined inside module. So _lv_i18n_init()_ could use _lv_i18n_language_pack_ as default language pack if argument is NULL, or initilize with some external language pack. To get options of language pack, such as number of languages and locale names in it we can use appropriate api-function.

**Comment by puzrin** [comment]
You describe what can be done, but don't explain WHY this should be done. IMO requested change will improve almost nothing, and i tend to reject "coding just for fun".

**Comment by glory-man** [comment]
Maybe I came from the wrong side. :) My first suggestion was to add into c-api count_locales and get_locale_name functions, which can be used in different application places to receive options of current_lang_pack.

**Comment by kisvegabor** [comment]
> Generated files lv_i18n.c/h implemented as an isolated module. To initilize module I need to call lv_i18n_init() with an argument value equal to lv_i18n_language_pack which is defined inside module. So lv_i18n_init() could use lv_i18n_language_pack as default language pack if argument is NULL, or initilize with some external language pack.

I do see value in it. Normally you want to use the language pack from `lv_i18n.c` so there is no reason to make the user repeat it.

**Comment by puzrin** [comment]
> I do see value in it. Normally you want to use the language pack from lv_i18n.c so there is no reason to make the user repeat it.

IMO the size of this value is about zero. "the repeat" is done once per project, and not difficult.

Also, code can be generated/composed somehow different. No need to limit API for one way only, if benefit is not significant.

> Maybe I came from the wrong side. :) My first suggestion was to add into c-api count_locales and get_locale_name functions, which can be used in different application places to receive options of current_lang_pack.

I'm open to suggestions, but my first question is the same - need use cases to show notable added value for all (or for "many", at least).

**Comment by kisvegabor** [comment]
> Also, code can be generated/composed somehow different. No need to limit API for one way only, if benefit is not significant.

It's a backward compatible change, not a limitation.
```c
lv_i18n_init(NULL);
//Same as
lv_i18n_init(lv_i18n_language_pack);
```

**Comment by puzrin** [comment]
I see. IMO not enough to make changes. But i don't pretend to be project owner. If that not takes my time - do as you wish.

**Comment by glory-man** [comment]
> I'm open to suggestions, but my first question is the same - need use cases to show notable added value for all (or for "many", at least).

If we have multilanguage UI, we can provide user to change language. In this case we need to tell user names of available locales. Get_locales_number and get_locale_name functions made application code more flexible.

**Comment by puzrin** [comment]
That's certainly valid use case, but i don't understand why special method required. User could create entry `my_locale_name` and iterate language pack, using `lv_i18n_set_locale(lang_pack_entry.locale_name) + _(my_locale_name)`.

As far as i understand, you propose to have special method call instead of `lv_i18n_set_locale(..) + _(..)` call. Doesn't look like significant simplificatrion.

**Comment by glory-man** [comment]
> That's certainly valid use case, but i don't understand why special method required. User could create entry `my_locale_name` and iterate [language pack](https://github.com/lvgl/lv_i18n/blob/8bf1fd3ab37251667be11f27efcadb1ae8cd3e25/src/lv_i18n.template.c#L114), using `lv_i18n_set_locale(lang_pack_entry.locale_name) + _(my_locale_name)`.
> 
> As far as i understand, you propose to have special method call instead of `lv_i18n_set_locale(..) + _(..)` call. Doesn't look like significant simplificatrion.

Such methods will increase the level of abstraction from the internal implementation of language pack.
For example, If I want to recieve parent of  `obj` in lvgl-library `obj->parent` helps me, but I prefer to call `lv_obj_get_parent(obj)`

**Comment by puzrin** [comment]
I follow different principle - if something is doable without api change => no changes needed. That helps to keep api clean.

Also, i don't like to reinvent the wheel. This package tries to follows gettext subset. If you say "we need feature X from gettext" - that's ok. If you don't know gettext and try to reinvent your own feature - that's not ok.

**Comment by kisvegabor** [comment]
@puzrin [lv_i18n.template.c](https://github.com/lvgl/lv_i18n/blob/master/src/lv_i18n.template.c) is used as template for the final `lv_i18n.c`, right? So anything we add there will be in the final C file?

**Comment by puzrin** [comment]
All except sample data `/*SAMPLE_START*/` ... `/*SAMPLE_END*/`

**Comment by kisvegabor** [comment]
Thanks!

I've added it here: https://github.com/lvgl/lv_i18n/commit/cbfe106994ff0dd7b7d4362a36faa45c1a1808ea

**Comment by puzrin** [comment]
CI tests failed

**Comment by kisvegabor** [comment]
Fixed.
