### ISSUE TITLE
After reading your README, I don't know how to use LV_i18n. Can you describe it in more detail

### ISSUE THREAD

**Issue by jianjunxia** [lvgl/lv_i18n#40]

**Comment by puzrin** [comment]
Sorry, no personal consultations in tracker. Try to as at forum, may be someone have time to help.

**Comment by jianjunxia** [comment]
> Sorry, no personal consultations in tracker. Try to as at forum, may be someone have time to help.

Can you give a link to the forum? thanks

**Comment by embeddedt** [comment]
https://forum.lvgl.io/
