### ISSUE TITLE
why i use npx lv_i18n -h installation is successful, but the lv_i18n command cannot be found，please help!

### ISSUE THREAD

**Issue by jianjunxia** [lvgl/lv_i18n#41]
when i use npx lv_i18n -h
in my terminal shows:
npx: 31 安装成功，用时 15.999 秒
usage: lv_i18n [-h] [-v] {extract,compile,rename} ...
optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit

Known commands:
  {extract,compile,rename}

See 'lv_i18n <command> -h' for more information on specific command

**but i use "lv_i18n -h" ,it shows not fond this cmd**. please help me  i feel sad~

**Comment by puzrin** [comment]
If you installed to local dir, use `lv_i18n.js` instead. Local install does not create [shortcut](https://github.com/lvgl/lv_i18n/blob/master/package.json#L17).

**Comment by jianjunxia** [comment]
> If you installed to local dir, use `lv_i18n.js` instead. Local install does not create [shortcut](https://github.com/lvgl/lv_i18n/blob/master/package.json#L17).
yes,i use npm init private npm i lv_i18n -s in my project,thanks help me ,i will try it

**Comment by embeddedt** [comment]
If you are trying to use it like a normal command, I recommend using `npm install -g lv_i18n`. This will install one version globally, similarly to how `apt` and other package managers work.

Local installation makes more sense if you are using it in an existing Node.js-based project.
