### ISSUE TITLE
 other: %d users are logged in - reason: 'bad indentation of a mapping entry',

### ISSUE THREAD

**Issue by Coffeeye** [lvgl/lv_i18n#44]
Iam trying to use your example but running convert gives me error (bcs of "%d")

```
  reason: 'bad indentation of a mapping entry',
  mark: Mark {
    name: '../../main/display/translations/en-GB.yml',
    buffer: "'en-GB':\r\n" +
      '  title1: Main menu\r\n' +
      '  user_logged_in:\r\n' +
      '    one: One user is logged in\r\n' +
      '    other: %d users are logged in\n' +
      '\x00',
    position: 93,
    line: 4,
    column: 11
  }
}
```

**Comment by puzrin** [comment]
Thanks for info. Fixed.

http://nodeca.github.io/js-yaml/#yaml=b3RoZXI6ICclZCB1c2VycyBhcmUgbG9nZ2VkIGluJw==

Some strings with special chars should be quoted. Use online demo to ensure result is as you expect.

**Comment by Coffeeye** [comment]
Cause another error see [FIX](https://github.com/lvgl/lv_i18n/commit/efde928db87cc890608c44dd412e894586eb14be)

**Comment by puzrin** [comment]
That's not error. It returns proper plural form of string, and then you can post-process it as you need.

**Comment by Coffeeye** [comment]
so the number in the middle brackets doesn't really make a difference, does it?
