### ISSUE TITLE
feature: use yawn-yaml to keep comments in translation

### ISSUE THREAD

**Issue by bubeck** [lvgl/lv_i18n#51]
Are you willing to accept a PR to change (mainly translation-keys) to use https://github.com/mohsen1/yawn-yaml instead of yaml to keep comments within the language files. This allows translators or developers to exchange questions/ideas/hints for translation without loosing them on next "extract"?

The next step could be to extend "extract" to generate a comment for a key to include a URL to point to the source code positions, where the translation is used. Something like https://github.com/lvgl/lv_i18n/blob/master/src/lv_i18n.template.c#L103

**Comment by puzrin** [comment]
I see no problem to change dependency as part of comments support PR, if that's required.

**Comment by JeremiahGillis** [comment]
I agree that comment support would be nice. Comments currently get deleted when running `extract`.
