### ISSUE TITLE
[question] Does this support changing labels lang at runtime?

### ISSUE THREAD

**Issue by teaalltr** [lvgl/lv_i18n#60]
Sorry for the potentially silly question but I'm a bit confused. Does this lib support changing the lang at runtime or is it just a compile-time thing?
Thank you! @seyyah @puzrin @kisvegabor

**Comment by kisvegabor** [comment]
It can be changed in runtimet too, by calling `lv_i18n_set_locale("...")` again. However you need to set the texts of the labels again because e.g. `lv_label_set_text(label, _("dog"));` set the previous translation of "dog".
