### ISSUE TITLE
error-text variable substitution failure

### ISSUE THREAD

**Issue by bryghtlabs-richard** [lvgl/lv_i18n#62]
I would like to see what translations have been loaded into lv_i18n, so that I can correct either my specified base language(-l) or correct the language names(??.yml), but it always prints {locale-name} instead:

```
C:\...\>dir translations\*.yml
 Volume in drive C is OS
 Volume Serial Number is 561D-A61E

 Directory of C:\...\translations
07/10/2024  08:58 AM               698 de.yml
07/10/2024  08:58 AM               698 en.yml
07/10/2024  08:58 AM               698 es.yml
07/10/2024  08:58 AM               698 fr.yml
07/10/2024  08:58 AM               698 it.yml
               5 File(s)          3,490 bytes
C:\...\>lv_i18n compile -l en -t translations\*.yml
You specified base locale "en", but it was not found in loaded translations.
Found locales are {locale-name}.
```

**Comment by kisvegabor** [comment]
It seems it's printed incorrectly [here](https://github.com/lvgl/lv_i18n/blob/8904107f57ddda3345394bfac466df975631aaa5/lib/cmd_compile.js#L72). 

cc @puzrin

**Comment by bryghtlabs-richard** [comment]
I was confused and did not have my yml files set up correctly. When the documentation said to replace "language-code with the actual language code", I didn't know what to do, because I didn't have a "language-code", I only had a "locale-name". After updating the documentation slightly, I was able to follow the steps and get it working.

But now I see, it does seem like maybe there are some extra {} being printed.
