### ISSUE TITLE
readme: build status image link is down

### ISSUE THREAD

**Issue by bryghtlabs-richard** [lvgl/lv_i18n#64]
https://github.com/lvgl/lv_i18n/blob/master/README.md references https://img.shields.io/travis/lvgl/lv_i18n/master.svg?style=flat, but it results in a 404:BadgeNotFound error

**Comment by kisvegabor** [comment]
I'm don't the capacity to maintain this repo right now, I hope @puzrin can take look.

Or if someone is interested in joining as a maintainer, it would be highly appreciated. Normally there are only a few issues in this repo.

**Comment by bubeck** [comment]
There is now a github action, that executes all tests. You can see the status in the Actions Tab,
